name: quimify_client
description: Quimify Client

version: 3.1.0+50 # Only for Android

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter_native_splash: ^2.2.8
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  http: ^0.13.5
  url_launcher: ^6.1.5
  photo_view: ^0.14.0
  flutter_easyloading: ^3.0.5
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"
  flutter_lints: ^2.0.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/https/certificate.crt
    - assets/https/private.key

    - assets/images/icons/logo.png
    - assets/images/icons/search.png
    - assets/images/icons/branding-slim.png
    - assets/images/icons/lock.png
    - assets/images/icons/2-chloroethylbenzene.png
    - assets/images/icons/molecule.png
    - assets/images/icons/calculator.png
    - assets/images/icons/report.png
    - assets/images/icons/narrow-arrow.png
    - assets/images/icons/scale.png
    - assets/images/dietanoic-acid.png
    - assets/images/icons/bond-carbon.png
    - assets/images/icons/hydrogenate.png
    - assets/images/icons/single-bond.png
    - assets/images/icons/double-bond.png
    - assets/images/icons/triple-bond.png
    - assets/images/icons/straight-radical.png
    - assets/images/icons/iso-radical.png
    - assets/images/icons/phenol.png
    - assets/images/icons/4-ethyl-2-methylhexane.png
    - assets/images/icons/2-methylpropane.png

  fonts:
    - family: CeraPro
      fonts:
        - asset: assets/fonts/CeraProBlack.otf
          weight: 900
        - asset: assets/fonts/CeraProBold.otf
          weight: 800
        - asset: assets/fonts/CeraProMedium.otf
          weight: 600
        - asset: assets/fonts/CeraProRegular.otf
          weight: 500
        - asset: assets/fonts/CeraProLight.otf
          weight: 300
        - asset: assets/fonts/CeraProThin.otf
          weight: 100
        - asset: assets/fonts/CeraProBlackItalic.otf
          style: italic
          weight: 900
        - asset: assets/fonts/CeraProBoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/CeraProMediumItalic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/CeraProRegularItalic.otf
          style: italic
          weight: 400
        - asset: assets/fonts/CeraProLightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/CeraProThinItalic.otf
          style: italic
          weight: 100

flutter_icons:
  image_path: "assets/images/launcher_icons/logo_white_extended.png"
  ios: true
  android: false # Adaptive icons have been manually added
  web:
    generate: true
    image_path: "assets/images/logo_white.png"

# The "flutter_lints" package below contains a set of recommended lints to
# encourage good coding practices. The lint set provided by the package is
# activated in the `analysis_options.yaml` file located at the root of your
# package. See that file for information about deactivating specific lint
# rules and activating additional ones.
flutter_lints: ^2.0.0

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'
