name: quimify_client
description: Quimify client

version: 3.4.9+91 # Android build code

flutter:
  uses-material-design: true

  assets:
    - assets/ssl/isrg-x1.crt

    - assets/images/icons/logo.png
    - assets/images/icons/search.png
    - assets/images/icons/branding-slim.png
    - assets/images/icons/lock.png
    - assets/images/icons/2-chloroethylbenzene.png
    - assets/images/icons/molecule.png
    - assets/images/icons/calculator.png
    - assets/images/icons/report.png
    - assets/images/icons/narrow-arrow.png
    - assets/images/icons/scale.png
    - assets/images/dietanoic-acid.png
    - assets/images/icons/bond-carbon.png
    - assets/images/icons/hydrogenate.png
    - assets/images/icons/single-bond.png
    - assets/images/icons/double-bond.png
    - assets/images/icons/triple-bond.png
    - assets/images/icons/straight-radical.png
    - assets/images/icons/iso-radical.png
    - assets/images/icons/4-ethyl-2-methylhexane.png
    - assets/images/icons/2-methylpropane.png
    - assets/images/icons/propyl.png
    - assets/images/icons/butane-diagram.png
    - assets/images/icons/butane.png
    - assets/images/icons/but-2-ene.png
    - assets/images/icons/but-2-yne.png
    - assets/images/discord.png
    - assets/images/gmail.png

  fonts:
    - family: CeraProBoldCustom # To use 'Îž' as a triple bond indicator
      fonts:
        - asset: assets/fonts/CeraProBoldCustom.otf

    - family: CeraPro
      fonts:
        - asset: assets/fonts/CeraProBlack.otf
          weight: 900
        - asset: assets/fonts/CeraProBold.otf
          weight: 800
        - asset: assets/fonts/CeraProMedium.otf
          weight: 600
        - asset: assets/fonts/CeraProRegular.otf
          weight: 500
        - asset: assets/fonts/CeraProLight.otf
          weight: 300
        - asset: assets/fonts/CeraProThin.otf
          weight: 100
        - asset: assets/fonts/CeraProBlackItalic.otf
          style: italic
          weight: 900
        - asset: assets/fonts/CeraProBoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/CeraProMediumItalic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/CeraProRegularItalic.otf
          style: italic
          weight: 400
        - asset: assets/fonts/CeraProLightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/CeraProThinItalic.otf
          style: italic
          weight: 100

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter_native_splash: ^2.2.8
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  http: ^0.13.5
  url_launcher: ^6.1.5
  photo_view: ^0.14.0
  flutter_easyloading: ^3.0.5
  smooth_page_indicator: ^1.0.0+2
  flutter_typeahead: ^4.1.1
  envied: ^0.2.4
  diacritic: ^0.1.3
  collection: ^1.16.0
  mailto: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"
  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  envied_generator: ^0.2.3+1

# Icon:
flutter_icons:
  image_path: "assets/images/launcher_icons/logo-white-extended.png"
  ios: true
  android: false # Adaptive icons have been manually added
  web:
    generate: true
    image_path: "assets/images/logo-white.png"

# Flutter default:
flutter_lints: ^2.0.0
publish_to: 'none'
