name: cliente
description: Cliente de Quimify

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter_native_splash: ^2.2.8
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  http: ^0.13.5
  url_launcher: ^6.1.5
  photo_view: ^0.14.0
  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"
  flutter_lints: ^2.0.1

flutter_icons:
  image_path: "assets/images/launcher_icons/logo_white_extended.png"
  ios: true
  android: false # Adaptive icons have been manually added
  web:
    generate: true
    image_path: "assets/images/logo_white.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/icons/logo.png
    - assets/images/icons/search.png
    - assets/images/icons/branding_slim.png
    - assets/images/icons/lock.png
    - assets/images/icons/3-chloropropylbenzene.png
    - assets/images/icons/molecule.png
    - assets/images/icons/calculator.png
    - assets/images/icons/report.png
    - assets/images/icons/narrow_arrow.png
    - assets/images/icons/scale.png
    - assets/images/dietanoic-acid.png
    - assets/images/icons/bond_carbon.png
    - assets/images/icons/hydrogenate.png
    - assets/images/icons/iso-radical.png
    - assets/https/certificate.crt
    - assets/https/private.key

  fonts:
    - family: CeraPro
      fonts:
        - asset: assets/fonts/CeraProBlack.otf
          weight: 900
        - asset: assets/fonts/CeraProBold.otf
          weight: 800
        - asset: assets/fonts/CeraProMedium.otf
          weight: 600
        - asset: assets/fonts/CeraProRegular.otf
          weight: 500
        - asset: assets/fonts/CeraProLight.otf
          weight: 300
        - asset: assets/fonts/CeraProThin.otf
          weight: 100
        - asset: assets/fonts/CeraProBlackItalic.otf
          style: italic
          weight: 900
        - asset: assets/fonts/CeraProBoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/CeraProMediumItalic.otf
          style: italic
          weight: 500
        - asset: assets/fonts/CeraProRegularItalic.otf
          style: italic
          weight: 400
        - asset: assets/fonts/CeraProLightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/CeraProThinItalic.otf
          style: italic
          weight: 100
